# -*- coding: utf-8 -*-
"""sports headlines using selenium.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rnbPQI1HEn2QVfvNe5C_eTAEndgdxf3v
"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# # Ubuntu no longer distributes chromium-browser outside of snap
# #
# # Proposed solution: https://askubuntu.com/questions/1204571/how-to-install-chromium-without-snap
# 
# # Add debian buster
# cat > /etc/apt/sources.list.d/debian.list <<'EOF'
# deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main
# deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main
# deb [arch=amd64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main
# EOF
# 
# # Add keys
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A
# 
# apt-key export 77E11517 | gpg --dearmour -o /usr/share/keyrings/debian-buster.gpg
# apt-key export 22F3D138 | gpg --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg
# apt-key export E562B32A | gpg --dearmour -o /usr/share/keyrings/debian-security-buster.gpg
# 
# # Prefer debian repo for chromium* packages only
# # Note the double-blank lines between entries
# cat > /etc/apt/preferences.d/chromium.pref << 'EOF'
# Package: *
# Pin: release a=eoan
# Pin-Priority: 500
# 
# 
# Package: *
# Pin: origin "deb.debian.org"
# Pin-Priority: 300
# 
# 
# Package: chromium*
# Pin: origin "deb.debian.org"
# Pin-Priority: 700
# EOF
# 
# # Install chromium and chromium-driver
# apt-get update
# apt-get install chromium chromium-driver
# 
# # Install selenium
# pip install selenium

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.headless = True
wd = webdriver.Chrome('chromedriver',options=chrome_options)
wd.get("https://www.thesun.co.uk/sport/football")
# service = Service(executable path)

containers = wd.find_elements(by="xpath", value='//div[@class ="teaser__copy-container"]')

titles =[]
subtitles = []
links =[]

for container in containers:
  title = container.find_element(by = 'xpath', value='./a/h3').text
  subtitle = container.find_element(by = 'xpath', value='./a/p').text
  link = container.find_element(by = 'xpath', value='./a').get_attribute('href')
  titles.append(title)
  subtitles.append(subtitle)
  links.append(link)

import pandas as pd

mydictionary = {"Titles": titles, "Subtitles": subtitles,"Links": links}

df_headlines = pd.DataFrame(mydictionary)

df_headlines.head()

import sys

import os

from datetime import datetime

application_path = os.path.dirname(sys.executable)

now = datetime.now()
day = now.strftime('%d%m%Y')

fname = f'Headlines-{day}.csv'

path = os.path.join(application_path, fname)

df_headlines.to_csv(path)

wd.quit()



